name: Print Software Versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  PrintAppPlatformVersions:
    name: Print Application Platform Versions
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js Version
        run: node --version

      - name: Print npm Version
        run: npm --version

      - name: Print OS Version
        run: lsb_release -a || cat /etc/os-release
        
      - name: Print Java Version
        run: java -version


  PrintDBMSVersions:
    name: Print Database Server Versions
    runs-on: ubuntu-latest
    needs: [PrintAppPlatformVersions]
    steps:
      - name: Print MongoDB Version (Docker)
        run: docker run --rm mongo:6.0 mongod --version
